version: "3"

services:

  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile.dev
    command: npm start
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./frontend:${FRONTEND_DIRECTORY}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MERCURE_PUBLISH_URL=${MERCURE_PURL_LOCAL}

  api:
    build:
      dockerfile: ../docker/api/php/Dockerfile_xdebug.local
    volumes:
      - ./docker/api/php/cronfiles:/cronfiles
      - ./docker/api/php/supervisor:/etc/supervisor.d
      - ./docker/api/php/config/docker-opcache.ini:/usr/local/etc/php/conf.d/docker-opcache.ini
      - ./docker/api/php/config/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-xdebug.ini
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: "client_host=172.22.0.1"
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql

  nginx:
    restart: unless-stopped
    volumes:
      - ./docker/certs/local:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: dev
      NGINX_HOST: ${NGINX_HOST_LOCAL}
      NGINX_PORT: ${NGINX_PORT_LOCAL}
      NGINX_CERT_CRT: ${NGINX_CERT_CRT_LOCAL}
      NGINX_CERT_KEY: ${NGINX_CERT_KEY_LOCAL}
      NGINX_MERCURE_IP: ${MERCURE_IPV4}

  mysql:
    image: mysql:8.0.20
    container_name: exchanger-mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #login:root password:root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    hostname: mysql.docker
    networks:
      exchanger:
        ipv4_address: ${MYSQL_IPV4}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: exchanger-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_ROOT_PASSWORD}
      MYSQL_USER: ${PHPMYADMIN_MYSQL_USER}
      MYSQL_PASSWORD: ${PHPMYADMIN_MYSQL_PASSWORD}
      UPLOAD_LIMIT: 100M
    networks:
      exchanger:
        ipv4_address: ${PHPMYADMIN_IPV4}

  redis:
    build:
      context: ./docker/redis
    container_name: exchanger-redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      exchanger:
        ipv4_address: ${REDIS_IPV4}

volumes:
  nginx:
  redis:
  mysql:
    driver: "local"
