version: "3"

services:

  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile.prod
    restart: always
    command: serve -s build -l 3000
    environment:
      - NODE_ENV=prod
      - MERCURE_PUBLISH_URL=${MERCURE_PURL_PROD}

  api:
    restart: always
    environment:
      - NODE_ENV=prod
    volumes:
      - ./docker/api/php/cronfiles:/cronfiles
      - ./docker/api/php/supervisor:/etc/supervisor.d
      - ./docker/api/config/docker-opcache.ini:/usr/local/etc/php/conf.d/docker-opcache.ini

  nginx:
    restart: always
    volumes:
      - ./docker/certs/prod:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: prod
      NGINX_HOST: ${NGINX_HOST_PROD}
      NGINX_PORT: ${NGINX_PORT_PROD}
      NGINX_CERT_CRT: ${NGINX_CERT_CRT_PROD}
      NGINX_CERT_KEY: ${NGINX_CERT_KEY_PROD}
      NGINX_MERCURE_IP: ${MERCURE_IPV4}

  redis:
    build:
      context: ./docker/redis
    container_name: exchanger-redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      exchanger:
        ipv4_address: ${REDIS_IPV4}



volumes:
  redis:
  nginx:
    driver: "local"
