api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            client_items_per_page: true
            items_per_page: 200
    formats:

        jsonld:    ['application/ld+json']
        json:      ['application/json']
        html:      ['text/html']
    # Allow using plain IDs for JSON format
#    allow_plain_identifiers: true
    eager_loading:
        # To enable or disable eager loading.
        enabled: true
        fetch_partial: false
        max_joins: 30
        force_eager: true
    exception_to_status:
#        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 400
