doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            uuid_binary:  Ramsey\Uuid\Doctrine\UuidBinaryType
            uuid_binary_ordered_time:  Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid: uuid
            uuid_binary: binary
            uuid_binary_ordered_time: binary

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        metadata_cache_driver: ~

        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool

        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
