lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 28800

#    token_extractors:
#        query_parameter:
#            enabled: true
#            name: bearer
#
#        # look for a token as Authorization Header
#        authorization_header:
#            enabled: false
#            prefix: Bearer
#            name: Authorization
#
#        # check token in a cookie
#        cookie:
#            enabled: false
#            name: BEARER
